apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command: ["rabbitmqctl", "stop_app"]
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: {{ default "admin" .Values.auth.username | quote }}
        - name: RABBITMQ_DEFAULT_PASS
          value: {{ required "A valid RabbitMQ password is required!" .Values.auth.password | quote }}
        - name: RABBITMQ_NODENAME
          value: "rabbit@localhost"
        - name: RABBITMQ_MEM_LIMIT
          value: "419430400" 
        ports:
        - name: amqp
          containerPort: 5672
        - name: management
          containerPort: 15672
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1"