replicaCount: 2
image:
  repository: telemetry-collector
  tag: v1
  pullPolicy: Never

tenant:
  id: "Alpha-Tenant"
  label: "alpha"

service:
  port: 80
  targetPort: 8000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"

readinessProbe:
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

livenessProbe:
  path: /health
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3