{{- if eq .Values.workloadType "test" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-workload
  labels:
    app: {{ .Release.Name }}
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          {{- if .Values.resources }}
          resources: {{ toYaml .Values.resources | indent 12 }}
          {{- end }}
          {{- if .Values.env }}
          env:
          {{- range $key, $val := .Values.env }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end }}
          {{- end }}
{{- end }}